#!/usr/bin/env bash
# installing a load balancer


sudo apt-get -y update
sudo apt-get -y install haproxy

server_config=\
"

frontend hendy-frontend
	 bind *:80
 	 mode http
	 default_backend hendy-backend

backend sage-backend
 	balance roundrobin
 	server 104361-web-01 52.3.255.135 check
	server 104361-web-02 52.86.225.142 check
"
echo "$server_config" |sudo tee -a /etc/haproxy/haproxy.cfg
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
sudo service haproxy restart
